data:
  input_file: "input_data.csv"
  prepared_file: "prepared_data.csv"
  output_file: "output_data.csv"

target_column: "TARGET"

model_name: "random_forest"
model_params:
  n_estimators: 50
  max_depth: 10

stratify: false
test_size: 0.2
