ProcessingJobName: "${JOB_NAME}"
RoleArn: "${ROLE_ARN}"
AppSpecification:
  ContainerEntrypoint:
    - poetry
    - run
    - pipeline
ProcessingResources:
  ClusterConfig:
    InstanceCount: 1
    InstanceType: "${INSTANCE_TYPE}"
    VolumeSizeInGB: ${VOLUME_SIZE_IN_GB}
Environment:
  AWS_REGION: "${AWS_REGION}"
  EXECUTION_ENV: aws
  DEPLOYMENT_ENV: "${DEPLOYMENT_ENV}"
  SNOWFLAKE_ACCOUNT: "${SNOWFLAKE_ACCOUNT}"
  SNOWFLAKE_USER_DEV: "${SNOWFLAKE_USER_DEV}"
  SNOWFLAKE_USER_PROD: "${SNOWFLAKE_USER_PROD}"
  SNOWFLAKE_ROLE_DEV: "${SNOWFLAKE_ROLE_DEV}"
  SNOWFLAKE_ROLE_PROD: "${SNOWFLAKE_ROLE_PROD}"
  SNOWFLAKE_WAREHOUSE: "${SNOWFLAKE_WAREHOUSE}"
  SNOWFLAKE_DATABASE_DEV: "${SNOWFLAKE_DATABASE_DEV}"
  SNOWFLAKE_DATABASE_PROD: "${SNOWFLAKE_DATABASE_PROD}"
  SNOWFLAKE_SCHEMA: "${SNOWFLAKE_SCHEMA}"
  MLFLOW_TRACKING_URI: "${MLFLOW_TRACKING_URI}"
  MLFLOW_MLRUNS_BUCKET: "${MLFLOW_MLRUNS_BUCKET}"
  MLFLOW_MLRUNS_PREFIX: "${MLFLOW_MLRUNS_PREFIX}"
