/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health
         * @description Report whether the API is serving and whether a model is loaded.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover the features a prediction needs
         * @description Describe the model's inputs, read from its logged signature.
         *
         *     A frontend calls this to build its prediction form, so that changing dataset
         *     changes the form without any code change.
         */
        get: operations["predict_schema_api_predict_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict for a single record
         * @description Predict for one set of feature values.
         *
         *     Raises:
         *         HTTPException: 422 if the submitted features do not match the model
         *             signature, listing exactly which names were missing or unknown.
         */
        post: operations["predict_api_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pick up a newly trained model version
         * @description Drop the cached model so the newest registered version is loaded.
         *
         *     A server holds one model in memory for the life of the process, so training
         *     a new version while the API runs would otherwise keep serving the old one
         *     indefinitely. This makes that recoverable without a restart.
         *
         *     Raises:
         *         HTTPException: 503 if no model can be loaded after clearing the cache.
         */
        post: operations["reload_model_api_predict_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List runs
         * @description List runs for the configured experiment, newest first.
         *
         *     Returns an empty list rather than an error when nothing has been logged, so
         *     a dashboard can render an empty state instead of handling a failure.
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one run
         * @description Return a single run with its metrics, parameters, and tags.
         *
         *     Raises:
         *         HTTPException: 404 if the run does not exist.
         */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a run
         * @description Delete one run from MLflow.
         *
         *     This is a soft delete on MLflow's side (the run moves to its deleted-run
         *     view rather than disappearing outright), which is enough to drop it out of
         *     the dashboard's listing without touching artifact storage here.
         *
         *     Raises:
         *         HTTPException: 404 if the run does not exist.
         */
        delete: operations["delete_run_api_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a run's artifacts
         * @description List artifacts logged against a run, optionally within a subdirectory.
         */
        get: operations["list_artifacts_api_runs__run_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/artifacts/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download one artifact file
         * @description Serve a single artifact file, such as an EDA plot.
         *
         *     ``path`` comes from the client, so it is never joined onto the filesystem
         *     directly. It is checked against the run's own artifact listing first, and
         *     the resolved file must still sit inside the download directory. Without both
         *     checks this endpoint would be a path-traversal hole.
         *
         *     Raises:
         *         HTTPException: 404 if the run or artifact does not exist, 400 if the
         *             path escapes the artifact tree.
         */
        get: operations["get_artifact_file_api_runs__run_id__artifacts_file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactEntry
         * @description One file or directory logged against a run.
         */
        ArtifactEntry: {
            /**
             * Path
             * @description Path relative to the run's artifact root.
             */
            path: string;
            /** Is Dir */
            is_dir: boolean;
            /** File Size */
            file_size?: number | null;
        };
        /**
         * ErrorResponse
         * @description A failed request. FastAPI uses ``detail`` for its own errors too.
         */
        ErrorResponse: {
            /**
             * Detail
             * @description Human-readable explanation of the failure.
             */
            detail: string;
        };
        /**
         * FeatureSpecResponse
         * @description One input the model expects, described so a UI can render a control.
         */
        FeatureSpecResponse: {
            /**
             * Name
             * @description Feature name, as the model expects it.
             */
            name: string;
            /**
             * Mlflow Type
             * @description MLflow schema type, e.g. 'double'.
             */
            mlflow_type: string;
            /**
             * Kind
             * @description Coarse type for widget selection: number, integer, boolean, string, or datetime.
             */
            kind: string;
            /**
             * Required
             * @description Whether a prediction request must set it.
             */
            required: boolean;
            /**
             * Example
             * @description Representative value from the logged input example, suitable for pre-filling a form. Null if unavailable.
             */
            example?: unknown;
        };
        /**
         * HealthResponse
         * @description Liveness and readiness of the service and its dependencies.
         */
        HealthResponse: {
            /**
             * Status
             * @description 'ok' when the API itself is serving.
             */
            status: string;
            /**
             * Mlflow Tracking Uri
             * @description Tracking server the API reads.
             */
            mlflow_tracking_uri: string;
            /**
             * Model Available
             * @description Whether a registered model could be loaded. False on a fresh checkout until the training pipeline has run.
             */
            model_available: boolean;
            /**
             * Model Name
             * @description Registered model name, when one is loaded.
             */
            model_name?: string | null;
            /**
             * Model Version
             * @description Registered model version, when one is loaded.
             */
            model_version?: string | null;
        };
        /**
         * ModelReloadResponse
         * @description Which model version is in memory after a reload.
         */
        ModelReloadResponse: {
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /**
             * Reloaded
             * @description Always true; a failure returns an error instead.
             * @default true
             */
            reloaded: boolean;
        };
        /**
         * PredictRequest
         * @description Feature values for a single prediction.
         *
         *     Keys are validated against the model signature when the request is handled,
         *     not statically, because the valid keys depend on the trained model.
         */
        PredictRequest: {
            /**
             * Features
             * @description Feature name to value. Call GET /api/predict/schema to discover the expected names and types.
             */
            features: {
                [key: string]: unknown;
            };
        };
        /**
         * PredictResponse
         * @description The model's answer for one record.
         */
        PredictResponse: {
            /**
             * Prediction
             * @description The predicted label or value.
             */
            prediction: unknown;
            /**
             * Probabilities
             * @description Per-class scores, when the estimator exposes predict_proba. Null for regressors and estimators without it.
             */
            probabilities?: {
                [key: string]: number;
            } | null;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
        };
        /**
         * PredictSchemaResponse
         * @description The prediction contract, discovered from the model signature.
         *
         *     A frontend reads this and builds its input form at runtime, so swapping
         *     datasets needs no frontend changes.
         */
        PredictSchemaResponse: {
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Features */
            features: components["schemas"]["FeatureSpecResponse"][];
        };
        /**
         * RunDetail
         * @description One MLflow run with its parameters and tags.
         */
        RunDetail: {
            /** Run Id */
            run_id: string;
            /** Run Name */
            run_name?: string | null;
            /** Status */
            status?: string | null;
            /**
             * Start Time
             * @description Unix epoch milliseconds, as MLflow reports it.
             */
            start_time?: number | null;
            /** End Time */
            end_time?: number | null;
            /**
             * Metrics
             * @description Final logged value per metric key. Keys depend on what the pipeline logged, so consumers should render whatever is present.
             */
            metrics?: {
                [key: string]: number;
            };
            /** Params */
            params?: {
                [key: string]: string;
            };
            /** Tags */
            tags?: {
                [key: string]: string;
            };
        };
        /**
         * RunSummary
         * @description One MLflow run, as listed in a dashboard.
         */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Run Name */
            run_name?: string | null;
            /** Status */
            status?: string | null;
            /**
             * Start Time
             * @description Unix epoch milliseconds, as MLflow reports it.
             */
            start_time?: number | null;
            /** End Time */
            end_time?: number | null;
            /**
             * Metrics
             * @description Final logged value per metric key. Keys depend on what the pipeline logged, so consumers should render whatever is present.
             */
            metrics?: {
                [key: string]: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No model available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    predict_schema_api_predict_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictSchemaResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No model available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    predict_api_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No model available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reload_model_api_predict_reload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelReloadResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No model available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No model available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No model available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_run_api_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No model available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_artifacts_api_runs__run_id__artifacts_get: {
        parameters: {
            query?: {
                /** @description Subdirectory to list. */
                path?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactEntry"][];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No model available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_artifact_file_api_runs__run_id__artifacts_file_get: {
        parameters: {
            query: {
                /** @description Artifact path, exactly as listed. */
                path: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No model available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
