name: Deploy

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select the environment'
        options:
          - Please Select
          - dev_data_0005
      version:
        type: string
        description: "Enter version"
        required: true

run-name: Template Deploy ${{ inputs.environment }} - ${{ inputs.version }}

jobs:
  deploy:
    name: deploy - ${{ inputs.environment }} - ${{ inputs.version }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    environment: ${{ inputs.environment }}

    env:
      AWS_GITHUB_ROLE: ${{ vars.AWS_GITHUB_ROLE }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0       # fetch all commits
          fetch-tags: true

      - name: Check Version
        run: |
          git show ${{ inputs.version }}

      - name: Configure AWS credentials
        if: env.AWS_GITHUB_ROLE != ''
        uses: aws-actions/configure-aws-credentials@f2e9d495b03c8294c97f731a3419cc72a206d05a # v5.1.0
        with:
          aws-region: "eu-west-2"
          role-to-assume: ${{ vars.AWS_GITHUB_ROLE }}
          role-session-name: ${{ inputs.environment }}
          role-duration-seconds: 900 # 5 Minutes
          unset-current-credentials: true

      - name: Environment Check
        run: |
            echo "Deploying to ${{ inputs.environment }}"

      - name: AWS Account Info
        run: |
          aws sts get-caller-identity

      - name: Prepare Yaml
        run: |
            export $(grep -v '^#' .${{ inputs.environment }}.env | xargs)
            envsubst < template.yml.tpl > template.yml
            cat template.yml

      - name: Create Processing Job
        run: |

            # Split Environment string
            ENV_TYPE=$(echo "${{ inputs.environment }}" | cut -d'_' -f1)
            ENV_ID=$(echo "${{ inputs.environment }}" | cut -d'_' -f3)

            aws sagemaker create-processing-job \
              --region eu-west-2 \
              --processing-job-name uk-$ENV_TYPE-00000$ENV_ID-template-${{ inputs.version }}-$(date +"%Y%m%d")-$(date +"%H%M%S") \
              --app-specification ImageUri=294553143120.dkr.ecr.eu-west-2.amazonaws.com/data-template:${{ inputs.version }} \
              --cli-input-yaml file://template.yml
